#!/bin/bash
##
## 
##                This source code is part of
## 
##                          Cell-Diff
## 
##   Exact computation of cell proliferation model distributions
## 
##                        VERSION 1.0.0
## Written by Joshua L. Phillips.
## Copyright (c) 2010-2016, Joshua L. Phillips.
## Check out http://www.cs.mtsu.edu/~jphillips/software.html for more
## information.
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
## 
## If you want to redistribute modifications, please consider that
## derived work must not be called official Cell-Diff. Details are found
## in the README & LICENSE files - if they are missing, get the
## official version at github.com/douradopalmares/cell-differentiation/.
## 
## To help us fund Cell-Diff development, we humbly ask that you cite
## the poster on the package - you can find them in the top README file.
## 
## For more info, check our website at
## http://www.cs.mtsu.edu/~jphillips/software.html
## 
##

rm .generation*
rm .build*
rm .expand*
rm .summary*
